quarkus.datasource.db-kind=mariadb
quarkus.datasource.jdbc.url=jdbc:mariadb://localhost:3306/warehouse
quarkus.datasource.username=root
quarkus.datasource.password=raja123raja123

# optional, lässt Hibernate Tabellen automatisch erstellen
quarkus.hibernate-orm.database.generation=update
